### PR TITLE
Continuous Integration 

### PR DESCRIPTION
**Pull request by grizzi**
### Finally some CI!

- An attempt to add **a bit** of continuous integration in the pipeline. Born out of the frustation of commiting style changes. 
- Based on `pre-commit` hooks. See a short introduction [here](https://interrupt.memfault.com/blog/pre-commit#continuous-integration-ci). 
- The pipeline should be installed locally so that the developer also commit formatted code. Then in theory the code should automatically pass all the tests. In this way we make sure that the code is always agreeing with a specific set of style rules.
- This changes a lot of file but it is only formatting: no code changes are introduced.

### TODOs
- [ ] add instructions on how to use `pre-commit`
- [ ] add the install and build step in the continuous integration (maybe to do in a separate PR)}?

### CODE REVIEW

**Comment by jk-ethz** [comment]
Uhh, that's some great initiative. Awesome!
We should maybe add this pipeline to the `install_dependencies.sh` such that it is directly active on all dev PCs.

This will probably require a lot of merge on our pending PRs now with all the changes it does to the files 😄

**Comment by jk-ethz** [comment]
Uhh, that's some great initiative. Awesome!
We should maybe add this pipeline to the `install_dependencies.sh` such that it is directly active on all dev PCs.

This will probably require a lot of merge on our pending PRs now with all the changes it does to the files 😄

**Comment by grizzi** [comment]
The positive aspect is that there shouldnt be too much merge conflicts as we at most reshuffle some code. I want to try adding a build step, so that we can also test the build process through the `install_dependencies.sh`

**Review by jk-ethz — APPROVED** [review]

**Comment by grizzi** [comment]
Should I merge this now and leave the more advanced CI for later on? This might take some time to setup correctly

**Comment by jk-ethz** [comment]
> Should I merge this now and leave the more advanced CI for later on? This might take some time to setup correctly

Yes, the sooner we have this the better!

**Pull request merged**
